### PR TITLE
Electron example app

### PR DESCRIPTION
**Pull request by jasongin**

### CODE REVIEW

**Review by vmoroz — APPROVED** [review]

**Comment by 239573049** [comment]
Hello, is it possible to provide a case of a third-party package like SK in this example?

**Comment by 239573049** [comment]
Third-party packages are used in most scenarios.

**Comment by 239573049** [comment]
What's stopping this PR?

**Comment by jasongin** [comment]
> What's stopping this PR?

I was thinking about adding 3rd-party packages. But there's no need to block the PR on that, it can be added separately.

**Pull request merged**
