### PR TITLE
Use new multiline strings and normalize line ends

### PR DESCRIPTION
**Pull request by vmoroz**
The code gen tests were failing on my machine because expected strings had LF line ends while generated strings had environment's CRLF.
In this PR the issue is addressed by calling the `ReplaceLineEndings()` for all expected strings to match current environment line endings.
Also, the expected strings are changed to be the new C# multiline strings.
They allow string text to be aligned with the rest of the code. The indentation is cut by the final `"""` indentation.

### CODE REVIEW

**Comment by jasongin** [comment]
I recommend fixing your git config so the line endings in your source files will be correct on Windows.

```
git config --global core.autocrlf true
```

https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

**Review by jasongin — APPROVED** [review]

**Comment by vmoroz** [comment]
> I recommend fixing your git config so the line endings in your source files will be correct on Windows.
> 
> ```
> git config --global core.autocrlf true
> ```
> 
> https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings

I cannot do it globally. Each OSS project has its own requirements.
We should add repo-specific settings if our code relies on it.

**Comment by jasongin** [comment]
> Each OSS project has its own requirements.

I'm surprised any project would require NOT using that setting, since it is widely recommended for use with git on Windows and I believe the installer for Windows now sets it by default.

Regardless, I'm fine with fixing our tests to be independent of the local newline environment, which is why I approved this PR.

**Comment by vmoroz** [comment]
> > Each OSS project has its own requirements.
> 
> I'm surprised any project would require NOT using that setting, since it is widely recommended for use with git on Windows and I believe the installer for Windows now sets it by default.
> 
> Regardless, I'm fine with fixing our tests to be independent of the local newline environment, which is why I approved this PR.

There are some projects that have heavy dependency on new lines to be LF. Especially if they generate code.  Their developers typically do not use Windows and not aware about the issues the code (mostly test code) might have on Windows machines.

**Pull request merged**
